networks:
  default:
    external:
      name: proxy

volumes:
  db-data:

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    command: postgres
    environment:
      POSTGRES_INITDB_ARGS: --data-checksums
    env_file:
      - ./.env
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/postgresql/data

  graphql:
    image: hasura/graphql-engine:v2.0.1
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - 80
    command: >
      /bin/sh -c "
      graphql-engine \
        serve \
        --server-port 80 \
        --enable-console \
        --access-key $HASURA_GRAPHQL_ADMIN_SECRET;
      "
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
      # HASURA_GRAPHQL_JWT_SECRET: $AUTH_JWT_SECRET
      HASURA_GRAPHQL_CORS_DOMAIN: https://vault.benderfactory.com
      HASURA_GRAPHQL_ENABLE_CONSOLE: false
